telekom/wurzel

README.md

fix: icon path for Wurzel Icon

fix: use main to get icon.png

---

Makefile

Run linting also when reuse lint is failing

ci: dont stop linting on reuse lint fail

---

tests/steps/qdrant/e2e_test.py
wurzel/steps/qdrant/step.py

- [Not needed for hotfix ] I have updated the documentation accordingly

fix epithermal sideeffect during retirement

---

REUSE.toml
pyproject.toml
tests/markdown_test.py
wurzel/exceptions.py
wurzel/utils/__init__.py
wurzel/utils/to_markdown/html2md.py

add html2md abstraction to utils

---

pyproject.toml
wurzel/utils/to_markdown/__init__.py
wurzel/utils/to_markdown/html2md.py

hotfix: add to include binaries into the package

---

wurzel/steps/__init__.py

- [x ] I have run the linter and ensured the code is formatted correctly

fix: remove accablabilty to milvus in init. Milvus causing  _ops issue

---

pyproject.toml
tests/settings/nesting_test.py
tests/step_executor/basic_test.py
tests/steps/qdrant/e2e_test.py
wurzel/steps/milvus/__init__.py
wurzel/steps/qdrant/__init__.py
wurzel/steps/qdrant/data.py
wurzel/steps/qdrant/step.py
wurzel/steps/qdrant/step_multi_vector.py
wurzel/utils/__init__.py

fix: add tlsh dep to qdrant

---

.github/workflows/publish-to-testpypi.yml
pyproject.toml

Chore: github action maintenance

chore: remove test-release dependency on semantic-release

---

Dockerfile
entrypoint.sh
pyproject.toml
tests/cli/gen_cli_call_test.py
tests/import_test.py
tests/step/step_creation_test.py
wurzel/cli/__init__.py
wurzel/cli/cmd_generate.py
wurzel/utils/meta_steps.py

fix : adapt wurzel for Dockerfile

---

tests/step/self_consuming_step_test.py
wurzel/datacontract/datacontract.py
wurzel/step/self_consuming_step.py
wurzel/step/typed_step.py
wurzel/step_executor/base_executor.py

feature : implement self consuming step

---

.github/workflows/create-docker-img.yml
Dockerfile
pyproject.toml
tests/step/self_consuming_step_test.py
wurzel/step_executor/base_executor.py

feat: push img to container registry

---

.github/workflows/create-docker-img.yml
examples/pipeline/Dockerfile
examples/pipeline/README.md

- build docker img for arm 
- update img in docs
- update example

doc: example pipline update docker img

---

tests/import_test.py
tests/steps/docling/test_docling_step.py
wurzel/steps/docling/__init__.py

fix the optional imports for docling
cc  @Deepankchoudhary

fix: docling optional imports

---

wurzel/steps/qdrant/step.py

add sha256 as default

---

tests/steps/embedding/e2e_test.py
wurzel/steps/embedding/step.py

There is a bug regarding inheritance of EmebeddingStep and its Huggingface & Prefixed counterparts

fix: embedding-step inheritance

---

tests/steps/docling/test_docling_step.py
wurzel/steps/docling/docling_step.py
wurzel/steps/docling/settings.py
wurzel/utils/to_markdown/html2md.py

DoclingStep was configured to drop/"clean" the headline what was wrong.

fix: docling

---

wurzel/steps/embedding/settings.py

closes: https://github.com/telekom/wurzel/issues/63

fix: e5 prefix default

---

wurzel/cli/cmd_inspect.py

fix: check optional settings before inspect

---

wurzel/datacontract/datacontract.py
wurzel/steps/docling/settings.py
wurzel/steps/milvus/settings.py
wurzel/steps/qdrant/settings.py

ref: pydantic deprecation warning

---

.github/workflows/create-docker-img.yml
.github/workflows/publish-to-pypi.yml

update naming for "pypi.org Release"

ref: rename workflow

---

pyproject.toml
wurzel/cli/_main.py
wurzel/cli/cmd_inspect.py

adding ruff rule: https://docs.astral.sh/ruff/rules/print/

ci: dont allow to use print

---

.github/workflows/test-docs.yml
docs/steps/splitter.md

- Add a new workflow to verify that the documentation builds correctly.
- Correct the existing documentation.

fix: docs & add workflows

---

wurzel/data/README.md

- Remove files that should not have been committed, empty...

fix: clean up wurzel folders

---

.github/dependabot.yml

- open one PR per dependency 
-  add docker 
- add github actions

ci: one pr for every dep
